name = "EPrimeData"
uuid = "6acf31e1-8949-4b86-8d0e-f99cc7606045"
authors = ["Oliver Lindemann"]
version = "0.1.1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
